In [8]:
# Q007 two dimentional Array
# 2019/12/4
# Tag: multidimensional array
# Description: Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element
#              value in the i-th row and j-th column of the array should be i*j.
#              Note: i=0,1.., X-1; j=0,1 !=Y-1.

# Example
# Suppose the following inputs are given to the program:
# 3,5
# Then, the output of the program should be:
# [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

# 描述：编写一个以2位X，Y为输入，生成二维数组的程序。元素数组的第i行和第j列中的值应为i*j。
# 注：i=0,1..，X-1；j=0,1！=Y-1。

# 例子
# 假设程序有以下输入：
# 3,5个
# 那么，程序的输出应该是：
# [[0，0，0，0，0]，[0，1，2，3，4]，[0，2，4，6，8]]

#coding=utf-8
import numpy as np
x = int(input("请输入列数："))
y = int(input("请输入行数："))
image =[[i*j for i in range(0,x)] for j in range(0,y)]
a = np.array(image)

print(a)

请输入列数：5
请输入行数：3
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [2]:
dimensions = [int(x) for x in input('x and y : ').split(',')]
rowNum = dimensions[0]
colNum = dimensions[1]

multiList = [[0 for col in range(colNum)] for row in range(rowNum)]

for row in range(rowNum):
    for col in range (colNum):
        multiList[row][col] = row * col

print(multiList)

x and y : 3,5
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]
