#  Python科学计算库Numpy概述

### 四个 python 库
+ Numpy 是用于科学计算，也就是进行矩阵计算（变换）,底层运算
+ Pandas 是以Numpy处理后的数据，进行计算
+ Matplotlib 可视化展示
+ Seabom 调用可视化模版

### python中的list是python的内置数据类型，list中的数据类不必相同的，而array的中的类型必须全部相同

In [1]:
import numpy as np

In [2]:
array = [1,2,3,4,5]
array + 1 # 列表数据不能全部加1

TypeError: can only concatenate list (not "int") to list

In [3]:
array = np.array([1,2,3,4,5]) # 把list转成ndarraym，可进行结算
print(type(array))

<class 'numpy.ndarray'>


In [4]:
array2 = array +1
array2

array([2, 3, 4, 5, 6])

In [5]:
array2+array #数组数据数目相同才可以相加

array([ 3,  5,  7,  9, 11])

In [6]:
array.shape #数组的行列数

(5,)

#### 列表与数组的区别
+ python中的list是python的内置数据类型，list中的数据类不必相同的，而array的中的类型必须全部相同

In [16]:
a=np.array((1,2,3,4,5))# 参数是元组  
b=np.array([6,7,8,9,0])# 参数是list  
c=np.array([[1,2,3],[4,5,6]])# 参数二维数组  
print (a,b) 
c.shape

[1 2 3 4 5] [6 7 8 9 0]


(2, 3)